//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbInstitution()
        {
            this.tbMaterial_Institution = new HashSet<tbMaterial_Institution>();
            this.tbTest = new HashSet<tbTest>();
            this.tbGroup = new HashSet<tbGroup>();
        }
    
        public System.Guid idInstitution { get; set; }
        public string Name { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Adress { get; set; }
    
        public virtual tbUser tbUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMaterial_Institution> tbMaterial_Institution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTest> tbTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGroup> tbGroup { get; set; }
    }
}
