//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLesson_Group
    {
        public System.Guid id_lesson { get; set; }
        public System.Guid id_group { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual tbGroup tbGroup { get; set; }
        public virtual tbLesson tbLesson { get; set; }
    }
}
