//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaterial_Institution
    {
        public System.Guid id_material { get; set; }
        public Nullable<System.Guid> id_institution { get; set; }
    
        public virtual tbInstitution tbInstitution { get; set; }
        public virtual tbMaterials tbMaterials { get; set; }
    }
}
