//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTaskResult
    {
        public string UserAnswer { get; set; }
        public Nullable<int> Rate { get; set; }
        public System.Guid id_task { get; set; }
        public System.Guid id_user { get; set; }
        public System.Guid id_test { get; set; }
    
        public virtual tbTask tbTask { get; set; }
        public virtual tbTest tbTest { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
