//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTaskVariant
    {
        public System.Guid id_task { get; set; }
        public string Name { get; set; }
        public bool isRight { get; set; }
        public System.Guid idTaskVariant { get; set; }
    
        public virtual tbTask tbTask { get; set; }
    }
}
