//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTest()
        {
            this.tbLesson = new HashSet<tbLesson>();
            this.tbTask = new HashSet<tbTask>();
            this.tbTaskResult = new HashSet<tbTaskResult>();
            this.tbTestResult = new HashSet<tbTestResult>();
            this.tbTask1 = new HashSet<tbTask>();
        }
    
        public System.Guid idTest { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> id_institution { get; set; }
        public Nullable<System.Guid> id_user { get; set; }
        public int Attempt { get; set; }
        public int TimeOnTest { get; set; }
    
        public virtual tbInstitution tbInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLesson> tbLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTask> tbTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTaskResult> tbTaskResult { get; set; }
        public virtual tbUser tbUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTestResult> tbTestResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTask> tbTask1 { get; set; }
    }
}
