//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProject.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInvite
    {
        public System.Guid idInvite { get; set; }
        public System.Guid id_group { get; set; }
    
        public virtual tbGroup tbGroup { get; set; }
    }
}
