//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationDbContext.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbLesson()
        {
            this.tbLesson_Group = new HashSet<tbLesson_Group>();
        }
    
        public System.Guid idLesson { get; set; }
        public Nullable<System.Guid> id_material { get; set; }
        public Nullable<System.Guid> id_test { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbLesson_Group> tbLesson_Group { get; set; }
        public virtual tbMaterials tbMaterials { get; set; }
        public virtual tbTest tbTest { get; set; }
    }
}
